### ISSUE TITLE
New Feature/research

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#114]
Instead of the map on the works page, Lorna would like some kind of decade browse. I am imagining something fairly simple that would look like the browse buttons but with more color. 

1: Ask Jess/Greg how easy it will be
2: Design mockup to fill in

**Comment by jduss4** [comment]
This might be kind of tricky, actually, because our API doesn't currently accommodate decades as facets (you can query a range of a decade, but there isn't a nice way to get a filterable list) so we would either need to add a custom field for decade or alter the API functionality.  Ultimately I think this is something we will need for other projects, also.

**Comment by jduss4** [comment]
Put the decade field into "topics" and this is done, minus a little bit of designing which is a different issue
