### ISSUE TITLE
sort dropdowns and multivalued select fields

### ISSUE THREAD

**Issue by jduss4** [CDRH/african_poetics#66]
I am guessing we can add a default to the models in terms of how results are returned
and that rails admin will respect that

**Comment by techgique** [comment]
So for small lists it looks like it just embeds the select options in the page:
![event-type-dropdown-embedded-options](https://user-images.githubusercontent.com/8347732/78399619-d9671600-75ba-11ea-87ea-c285c79860e9.png)

And for longer lists like Location, it makes an Ajax request for each time the input is focused:
![location-dropdown-ajax-request](https://user-images.githubusercontent.com/8347732/78399660-f00d6d00-75ba-11ea-918c-aecccbc1e0e1.png)

Not certain yet if changing the Ajax request, changing code server-side, or doing the sorting locally in JS is the best approach to sort alphabetically instead of descending ID sorting

**Comment by techgique** [comment]
This is controlled by the `sort_by :field` config for the `list` context
