### ISSUE TITLE
Featured Poet Publishing system

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#8]
Some of the poets will be "Featured" meaning they have more data/a bio written about them. 

Steps that need to be taken: 

- [x] Create sample HTML for ingesting (Karin)
- [x] Decide how to mark "featured" status in CSV, and how to link to the html
- [ ] Work on any HTML transforms (likely pretty minor, I'm not sure yet if they will include images)
- [x] Change ruby -> es ingest script to fill out html field
- [x] In rails, only show the html if there is something in the HTML field

ALTERNATELY, we could alter the csv - > html script to generate from the CSV and html at the same time?

**Comment by jduss4** [comment]
I don't think that the csv -> HTML script currently does anything, does it?  I figured the author pages were entirely assembled from the API content?  But I think, instinctively without trying anything out, that I would rather that the HTML for an author page be stored somewhere in the `source` files that would not be pulled automatically.  Maybe `source/annotations` or another directory?  And then the CSVs would either check against the filelist for a similar ID or there would be a column indicating "grab this document" which would index the content as text for ES or basically copy it to the output HTML directory.

**Comment by jduss4** [comment]
Right now I have it set up so that the CSV -> HTML script is merely copying the HTML files over to the output directory. If we need transformations for filling in environmental differences / more complicated stuff then I would recommend the following:

- if a minor transformation needed, use nokogiri and existing script to alter the HTML
- if a major transformation needed, change to HTML -> HTML script instead and use XSLT
