### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by karindalziel** [CDRH/african_poetics#90]
I was encountering broken links while clicking through the site, listing them here but need to check again once the databases are moved over

- https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/search?f%5B%5D=spatial.region%7CNorth+Africa
    - the result on that page is broken
- http://link.galegroup.com/apps/doc/ CS51007207/GDCS?u=linc74325&sid=GDCS&xid=04a3cf1d
- from this page https://cdrhdev1.unl.edu/african_poetics/inthenews/news/ap.news.632
    - Gale link broken 
    - looks like there's an extra space in it

**Comment by karindalziel** [comment]
https://cdrhdev1.unl.edu/african_poetics/inthenews/poets/ap.person.34

first person link, `Campbell, Roy (10)` is broken

**Comment by jduss4** [comment]
The first broken link was due to orphaned work roles, where there is an author, role, but not a work.  Therefore it was killing the UI.
That gale link is probably broken out there somewhere, but that link to dev1 is no longer available (that database is fluid and the entry has been deleted) so I will try to track it down.
Campbell, Roy (10) is working again.
